# Generated by Django 3.2 on 2023-02-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230216_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product_size',
            options={'verbose_name_plural': 'Product Sizes'},
        ),
    ]
